services:
  - type: web
    name: ai-research-summariser-backend
    env: docker
    dockerfilePath: docker/Dockerfile.backend
    plan: free
    region: ohio
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: ai-research-summariser-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: free
    region: ohio
    envVars:
      - key: VITE_API_URL
        value: ${ai-research-summariser-backend.url}
